[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MPSKitModels = "ca635005-6f8c-4cd1-b51d-8491250ef2ab"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StridedViews = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"
cuTENSOR = "011b41b2-24ef-40a8-b3eb-fa098493e9e1"

[compat]
StridedViews = "=0.4.1"
